version: "3.8"
services:
  app:
    build:
      args:
        user: lnwza
        uid: 1000
      context: ./Dockerfiles
      dockerfile: php8.0
    image: app-php
    container_name: app-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/php/php8.ini:/usr/local/etc/php/php.ini
    networks:
      - app

  mysql:
    image: mysql:5.7
    container_name: app-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql
    networks:
      - app

  nginx:
    image: nginx:alpine
    container_name: app-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - app

networks:
  app:
    driver: bridge